# Generated by Django 4.2.10 on 2024-02-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "iin",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="CriminalsData",
            fields=[
                (
                    "iin",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("dob", models.DateField()),
                ("martial_status", models.CharField(max_length=128)),
                ("offence", models.CharField(max_length=256)),
                ("zip_code", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Policeman",
            fields=[
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "iin",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("dob", models.DateField()),
                ("department", models.CharField(max_length=256)),
                ("badge_number", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
                ("username", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("action", models.TextField(blank=True, null=True)),
                (
                    "admin_logs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sketch.admin"
                    ),
                ),
                (
                    "policeman_logs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sketch.policeman",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriminalsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nose_len", models.FloatField(default=0)),
                ("right_brow_size", models.FloatField(default=0)),
                ("left_brow_size", models.FloatField(default=0)),
                ("left_eye_size", models.FloatField(default=0)),
                ("right_eye_size", models.FloatField(default=0)),
                ("nose_size", models.FloatField(default=0)),
                ("lips_size", models.FloatField(default=0)),
                (
                    "iin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sketch.criminalsdata",
                    ),
                ),
            ],
        ),
    ]
