# Generated by Django 4.2.10 on 2024-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0002_criminalsdata_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalsimage",
            name="normalized_feature",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Normalized Feature Array"
            ),
        ),
    ]
