# Generated by Django 4.2.10 on 2024-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0003_criminalsimage_normalized_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalsdata",
            name="gender",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Gender"
            ),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="dob",
            field=models.DateField(verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="first_name",
            field=models.CharField(max_length=128, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="iin",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                verbose_name="Personal Identification Number",
            ),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="last_name",
            field=models.CharField(max_length=128, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="martial_status",
            field=models.CharField(max_length=128, verbose_name="Martial Status"),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="offence",
            field=models.CharField(max_length=256, verbose_name="Charged offence"),
        ),
        migrations.AlterField(
            model_name="criminalsdata",
            name="zip_code",
            field=models.CharField(max_length=64, verbose_name="Zip code"),
        ),
    ]
