# Generated by Django 4.2.10 on 2024-04-06 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0004_criminalsdata_gender_alter_criminalsdata_dob_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criminalsdata",
            options={
                "verbose_name": "Criminal's Personal Data",
                "verbose_name_plural": "Criminals' Personal Data",
            },
        ),
        migrations.AlterModelOptions(
            name="criminalsimage",
            options={
                "verbose_name": "Criminal's Image Detail",
                "verbose_name_plural": "Criminals' Image Details",
            },
        ),
    ]
