# Generated by Django 4.2.10 on 2024-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0005_alter_criminalsdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaxMin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nose_len", models.FloatField(default=0)),
                ("right_brow_size", models.FloatField(default=0)),
                ("left_brow_size", models.FloatField(default=0)),
                ("left_eye_size", models.FloatField(default=0)),
                ("right_eye_size", models.FloatField(default=0)),
                ("nose_size", models.FloatField(default=0)),
                ("lips_size", models.FloatField(default=0)),
            ],
        ),
    ]
