# Generated by Django 4.2.10 on 2024-04-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0006_maxmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="maxmin",
            name="func_name",
            field=models.CharField(
                default="max", max_length=32, verbose_name="Max or Min"
            ),
        ),
    ]
