# Generated by Django 4.2.10 on 2024-04-11 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sketch", "0007_maxmin_func_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logs",
            name="admin_logs",
        ),
        migrations.RemoveField(
            model_name="logs",
            name="policeman_logs",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Logs",
        ),
        migrations.DeleteModel(
            name="Policeman",
        ),
    ]
